global:
  hosts:
    domain: your.gitlab.domain  # Replace with your actual domain or variable
    externalIP: your.external.ip # Replace with your actual IP or variable
  ingress:
    configureCertmanager: false
  rails:
    bootsnap:
      enabled: false
  kas:
    enabled: false

certmanager:
  install: false

prometheus:
  install: false

gitlab-runner:
  install: false

gitlab-exporter:
  enabled: false

toolbox:
  enabled: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    workerProcesses: 0
    resources:
      requests:
        memory: 600Mi

  sidekiq:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        memory: 300Mi
        cpu: 60m

  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1

  kas:
    minReplicas: 1
    maxReplicas: 1

registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
